# To use:
#
#   $ conda env create -f inflow_environment.yml
#   $ conda activate inflow
#
name: inflow
channels:
  - conda-forge
  - defaults
dependencies:
  - gdal
  - libgdal
  - netCDF4
  - pyproj
  - pytest-cov
  - python
  - pyyaml
  - rtree
  - scipy
  - shapely

